language: objective-c
osx_image: xcode9.3
branches:
  only: master
script:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
- set -o pipefail && xcodebuild -workspace Example/FBLeakDetectorVC.xcworkspace -scheme FBLeakDetectorVC-Example ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
- pod lib lint